### PR TITLE
DEV-639: ignore UTF8 BOM in holdings files

### PR DESCRIPTION
**Pull request by mwarin**
The file header line validation was not OK with there being non-printable characters in there. 
This change makes the validation ignore UTF-8 BOMs.

### CODE REVIEW

**Review by aelkiss — CHANGES_REQUESTED** [review]
It looks like there is a mechanism to automatically read the BOM or fall back to UTF-8:

https://ruby-doc.org/core-2.5.0/IO.html#method-c-new-label-IO+Encoding

```ruby
File.open("whatever.txt","r:BOM|UTF-8")
```

This should handle utf-16 without much rigmarole as well.

**Comment by aelkiss** [comment]
It looks like `Zinzout` should honor an "encoding" parameter - https://github.com/billdueber/zinzout/blob/master/lib/zinzout.rb - but worth verifying that it works.

**Comment by mwarin** [comment]
Can confirm that it is indeed possible to pass `encoding:"BOM|UTF-8"` via `ZinZout.zin` all the way to the underlying `IO`.

**Review by billdueber — APPROVED** [review]
All looks straightforward to me. TIL about `BOM|UTF-8`. Makes me wonder if I should put that as the default encoding for Zinzout, although apparently `StringIO` objects just ignore the BOM and you have to do some messing around. But so long as you're working with file-like objects this should be solid.

**Review by aelkiss — APPROVED** [review]
Looks good to me now.

**Comment by aelkiss** [comment]
Superceded by #263

**Comment by mwarin** [comment]
All important ideas here were incorporated into pr 263

**Pull request closed without merging**
