### PR TITLE
HT-2970 / HT-2940: Update last_modified iff something has changed

### PR DESCRIPTION
**Pull request by aelkiss**
See #86 ; merge after #86  / #88. Only relevant commit here is https://github.com/hathitrust/holdings-backend/pull/89/commits/7f882b4cacbaba32913f8b9572b3d5572f8372d8

- Adds tests for ensuring last modified changes when adding or updating
holdings, ocn resolution, ht items

- Only updates an ht item if something has actually changed

### CODE REVIEW

**Comment by aelkiss** [comment]
Updating holding with new UUID and date received should NOT update `last_modified`. We can keep the `last_modified` name.

**Comment by aelkiss** [comment]
Also we need to fix the holdings equality checking to compare all fields.

**Review by jsteverman — APPROVED** [review]
Changes in https://github.com/hathitrust/holdings-backend/commit/7f882b4cacbaba32913f8b9572b3d5572f8372d8 look good.
As discussed, we still need to handle the holdings updates.

**Comment by aelkiss** [comment]
Addressed cluster equality & last modified date issue and rebased.

**Review by jsteverman — APPROVED** [review]

**Pull request merged**
